md "todos os estados"
cd "todos os estados"
md "centro oeste" "nordeste" "norte" "sul" "sudeste"
cd "centro oeste"
md "Goias"
md "Mato Grosso"
md "Mato Grosso do Sul"
md "Distrito Federal"
cd ..
cd "nordeste"
md "Alagoas"
md "Bahia"
md "Ceara"
md "Maranhao"
md "Paraiba"
md "Pernambuco"
md "Piaui"
md "Rio Grande do Norte"
md "Sergipe"

