md "todos os clubes"
cd "todos os clubes"
md "serie A" "serie B"
cd "serie A"
md "Atletico MG"
md "Palmeiras"
md "Fortaleza"
md "Bragantino"
md "Flamengo"
md "Atletico PR"
md "Atletico GO"
md "Ceara"
md "Internacional"
md "Santos"
md "Corinthians"
md "Juventude"
md "Bahia"
md "Sao Paulo"
md "Fluminense"
md "Cuiaba"
md "Sport"
md "America MG"
md "Gremio"
md "Chapecoense"