md "todos os paises"
cd "todos os paises"
md "Argentina" "Bolivia" "Brasil" "Chile" "Colombia" "Equador" "Guiana" "Guiana Francesa" "Paraguai" "Peru" "Suriname" "Uruguai" "Venezuela" 
cd "Brasil"
md "Goias" "Mato Grosso" "Mato Grosso do Sul" "Distrito Federal" "Alagoas" "Bahia" "Ceara" "Maranhao" "Paraiba" "Pernambuco" "Piaui" "Rio Grande do Norte" "Sergipe" "Acre" "Amapa" Amazonas" "Para" "Rondonia" "Roraima" "Tocantins" "Parana" "Santa Catarina" "Rio Grande do Sul" "Sao Paulo" "Rio de Janeiro" "Espirito Santo" "Minas Gerais"
